import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class TelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form telaGerente
     */
    public TelaGerente(String nome, String cargo) {
        initComponents();
        //Jovem Aprendiz Só tem acesso de o gerente permitir.  
        lblSaudacao1.setText("Seja Bem-Vindo " + nome + " - Seu Cargo: " + cargo);
            if (cargo.equals("Gerente")|| cargo.equals("CEO")|| cargo.equals("Admin")){
                 mnuAdmin.setVisible(true);
                
         } else if(cargo.equalsIgnoreCase("Estagiario") ||  cargo.equalsIgnoreCase("Gerenciador de Caixa") || cargo.equalsIgnoreCase("Joven Aprendiz")){
              mnuEstoque.setEnabled(false);
              mnuAdmin.setEnabled(false);
              itmLucros.setEnabled(false);
           }else if (cargo.equalsIgnoreCase ("Estagiario") || cargo.equalsIgnoreCase("Estoquista")|| cargo.equalsIgnoreCase("Joven Aprendiz")){
                mnuAdmin.setEnabled(false);
               
                itmLucros.setEnabled(false);
                
           
           }
            
        
   }

    private TelaGerente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaudacao1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSaldacao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuEstoque = new javax.swing.JMenu();
        itmEstoquista = new javax.swing.JMenuItem();
        mnuAdmin = new javax.swing.JMenu();
        itmCadatrarUsuario = new javax.swing.JMenuItem();
        itmExluirUsuario = new javax.swing.JMenuItem();
        itmEditarUsuario = new javax.swing.JMenuItem();
        itmListaUsuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itmLucros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela do Gerente");
        getContentPane().setLayout(null);

        lblSaudacao1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(lblSaudacao1);
        lblSaudacao1.setBounds(130, 6, 500, 70);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblSaldacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldacao.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblSaldacao);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 340);

        mnuEstoque.setText("Estoque");

        itmEstoquista.setText("Tela de Estoquista ");
        itmEstoquista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEstoquistaActionPerformed(evt);
            }
        });
        mnuEstoque.add(itmEstoquista);

        jMenuBar1.add(mnuEstoque);

        mnuAdmin.setText("Admin");

        itmCadatrarUsuario.setText("Cadastrar Usuário");
        itmCadatrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadatrarUsuarioActionPerformed(evt);
            }
        });
        mnuAdmin.add(itmCadatrarUsuario);

        itmExluirUsuario.setText("Excluir Usuário");
        itmExluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExluirUsuarioActionPerformed(evt);
            }
        });
        mnuAdmin.add(itmExluirUsuario);

        itmEditarUsuario.setText("Editar Usuário");
        mnuAdmin.add(itmEditarUsuario);

        itmListaUsuarios.setText("Usuários do Sistema ");
        itmListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListaUsuariosActionPerformed(evt);
            }
        });
        mnuAdmin.add(itmListaUsuarios);

        jMenuBar1.add(mnuAdmin);

        jMenu1.setText("Caixa");

        itmLucros.setText("Lucros ");
        jMenu1.add(itmLucros);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Suporte");

        jMenuItem1.setText("Calculadora para suporte");
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem2.setText("Contato");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(754, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadatrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadatrarUsuarioActionPerformed
        TelaAdmin tela;
        tela = new TelaAdmin();
        tela.setVisible(true);
    }//GEN-LAST:event_itmCadatrarUsuarioActionPerformed

    private void itmExluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExluirUsuarioActionPerformed
        try {
           String u;
           u = JOptionPane.showInputDialog("Digite o usuario que deseja excluir");
            //2 - Conectar no banco de dados sistemabd;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemabd","root","084511");
            //3 - Buscar o usuário digitado na tabela usuario do banco de dados sistemabd;
            PreparedStatement st = conectado.prepareStatement("SELECT * FROM usuario WHERE usuario = ? ");
            st.setString(1, u);
            
            ResultSet resultado = st.executeQuery();
            //4 - Verificar se o usuário foi encontrado na tabela usuario do banco de dados.
            if(resultado.next()){
                //Abrir o formulário Menu.java
               String usuario, senha, nome, cargo;
               
               usuario = resultado.getString("usuario");
               senha = resultado.getString("senha");
               nome = resultado.getString("nome");
               cargo = resultado.getString("cargo");
               
                TelaAdmin tela;
                tela = new TelaAdmin(usuario, senha, nome, cargo);
                tela.setVisible(true);
                
                
            } else {
                JOptionPane.showMessageDialog(null,"Usuário Não cadastrado");
            }     
         
           //5 - Desconectar.
            conectado.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não está na library");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você errou nos dados da conexão com o banco de dados");
        }
    }//GEN-LAST:event_itmExluirUsuarioActionPerformed

    private void itmListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListaUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListaUsuariosActionPerformed

    private void itmEstoquistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEstoquistaActionPerformed
        TelaEstoquista tela;
        tela = new TelaEstoquista();
        tela.setVisible(true);
    }//GEN-LAST:event_itmEstoquistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadatrarUsuario;
    private javax.swing.JMenuItem itmEditarUsuario;
    private javax.swing.JMenuItem itmEstoquista;
    private javax.swing.JMenuItem itmExluirUsuario;
    private javax.swing.JMenuItem itmListaUsuarios;
    private javax.swing.JMenuItem itmLucros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblSaldacao;
    private javax.swing.JLabel lblSaudacao1;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuEstoque;
    // End of variables declaration//GEN-END:variables
}
